// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuQ5mX0e4colPkQsCkQ8KCELojPq3QAXM',
    appId: '1:562003157618:web:c1a0d9c158d956a609d8eb',
    messagingSenderId: '562003157618',
    projectId: 'myroomfinder-ecfd0',
    authDomain: 'myroomfinder-ecfd0.firebaseapp.com',
    storageBucket: 'myroomfinder-ecfd0.appspot.com',
    measurementId: 'G-KT9YR690TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRUl5Xl02AJRz4VOgrVencb2BFuBgVFB8',
    appId: '1:562003157618:android:e785aefe03d4fa6f09d8eb',
    messagingSenderId: '562003157618',
    projectId: 'myroomfinder-ecfd0',
    storageBucket: 'myroomfinder-ecfd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfidAszXRHtxYBXeJFBTdJ18CW8Q-Z03o',
    appId: '1:562003157618:ios:db1f67d733fca97409d8eb',
    messagingSenderId: '562003157618',
    projectId: 'myroomfinder-ecfd0',
    storageBucket: 'myroomfinder-ecfd0.appspot.com',
    iosBundleId: 'com.example.myroomfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfidAszXRHtxYBXeJFBTdJ18CW8Q-Z03o',
    appId: '1:562003157618:ios:db1f67d733fca97409d8eb',
    messagingSenderId: '562003157618',
    projectId: 'myroomfinder-ecfd0',
    storageBucket: 'myroomfinder-ecfd0.appspot.com',
    iosBundleId: 'com.example.myroomfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuQ5mX0e4colPkQsCkQ8KCELojPq3QAXM',
    appId: '1:562003157618:web:0e5505d596447fea09d8eb',
    messagingSenderId: '562003157618',
    projectId: 'myroomfinder-ecfd0',
    authDomain: 'myroomfinder-ecfd0.firebaseapp.com',
    storageBucket: 'myroomfinder-ecfd0.appspot.com',
    measurementId: 'G-B4QL2YPQHX',
  );
}
